  <footer  class="w3-container w3-center">
    <div id="social" class="w3-xlarge">
      <i class="fa fa-facebook-official w3-hover-opacity"></i>
      <i class="fa fa-instagram w3-hover-opacity"></i>
      <i class="fa fa-snapchat w3-hover-opacity"></i>
      <i class="fa fa-pinterest-p w3-hover-opacity"></i>
      <i class="fa fa-twitter w3-hover-opacity"></i>
      <i class="fa fa-linkedin w3-hover-opacity"></i>
    </div>
    <div id="footerMessage">
    <p>&copy; Dalton Consulting Pty Ltd.</p>
    <p>Please see our legal information page</p>
    </div>
  </footer>
  <script src="../js/stickyMenu.js"></script>
  <script>
  // <body onload="showLoader();" onunload="hideLoader();">
  //document.getElementsByTagname("body")[0].onload = function() {
  var showLoader = function() {
    <!-- Show Loader -->
    document.getElementById("loader").style.display="block";
    //document.getElementsByTagName("article")[0].style.display="none";
  }
  var hideLoader = function() {
    <!-- Hide Loader -->
    document.getElementById("loader").style.display="none";
    //document.getElementsByTagName("article")[0].style.display="block";
  }
  </script>
  <!-- <script src="../js/stickyMenu.js"></script> -->
</body>
</html>
